### ISSUE TITLE
url mit komma funktionieren nicht mehr

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/markitup#108]
kommas `,` in verlinkten url werden umgeschrieben in `%2C` und funktionieren dadurch nicht mehr.

**Comment by schorschy** [comment]
Komma bleibt bei mir Komma und wird nicht formatiert. Welche Version benutzt du?

**Comment by IngoWinter** [comment]
da @ansichtsache anscheinend das problem gelöst hat hier close
