### ISSUE TITLE
Ausgabe CSS und JavaScript im Backend optimieren

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/markitup#114]
Ausgabe CSS und JavaScript im Backend optimieren

Im Backend wird auf allen Seiten CSS+JavaScript für markitup geladen.
Sollte nur bei den notwendigen Seiten geladen werden!

**Comment by alxndr-w** [comment]
Außerdem scheint die Cache-JS-Datei bei jedem Seitenaufruf geschrieben zu werden, was das Prinzip Cache ad absurdum führt.

**Comment by christophboecker** [comment]
@alxndr-w Ich sah das hier grade: Das angesprochene Problem ("bei jedem Seitenaufruf geschrieben") müsste doch erledigt sein. Die Generierung ist schon 2018 aus der boot.php rausgeflogen (#80). Konntest Du mal rauskriegen, wo der Trigger ist, wenn es immer noch passiert?

Anders gesagt: ich kann den Fehler nicht reproduzieren.

**Comment by alxndr-w** [comment]
Ich auch nicht mehr. Dürfte ein Fremdprojekt von mir gewesen sein. Vielleicht auch ein altes rex_markitup.

Ich muss mir echt angewöhnen, dazuzuschreiben, was das dann jeweils für ein Projekt war. Nach einem halben Jahr weiß ich das nicht mehr.

**Comment by christophboecker** [comment]
Ha jo, geht mir auch so. Schöne Feiertage und nen guten Rutsch.

**Comment by alxndr-w** [comment]
Ich finde das ursprüngliche Issue nicht ohne Weiteres zu lösen, ohne alles komplexer zu machen. Prinzipiell kann Markitup überall im Backend auftauchen, auch in Add-ons und optional.

Das Problem, das gelöst werden soll, halte ich auch für nicht mehr so relevant. Bandbreite gibt's heutzutage genug. Https/2 macht das Laden auch schneller. Und 3 Jahre ungelöst scheint auch ein Indikator zu sein, nicht wichtig genug gewesen zu sein.
