### ISSUE TITLE
CSS-Optimierung bei Nutzung innerhalb yform und global_settings

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/markitup#115]
Bei der Verwendung von markitup innerhalb von yform-Tabellen und auch innerhalb des global_settings-AddOns gibt es noch unschöne Darstellungen:

<img width="648" alt="2021-02-14_13-31-41" src="https://user-images.githubusercontent.com/330160/107876895-26996100-6ec9-11eb-95f9-a9fa4aa66a06.png">

Lösen könnte man dies z.B. mit folgenden Ergänzungen im CSS des markitup-AddOns:

```
.rex-yform .markItUpContainer .markItUpHeader ul,
#rex-page-global-settings-settings .markItUpContainer textarea {
    margin-bottom: 0;
}
.rex-yform .markItUpContainer textarea,
#rex-page-global-settings-settings .markItUpContainer textarea {
    width: 100%;
}
```
Ich würde mich aber freuen, wenn insbesondere @christophboecker , @tbaddade und @skerbis noch einen Blick auf meinen Vorschlag werfen.

**Comment by skerbis** [comment]
Wenn man die markitup class kombiniert mit form-control aufruft sollte es eigentlich passen

**Comment by christophboecker** [comment]
Schnell getestet. Als Attribut der Textarea eingetragen: 
```json
{"class":"form-control markitupEditor-textile_full"}`
```
<img width="746" alt="grafik" src="https://user-images.githubusercontent.com/10065904/107877657-1932a580-6ece-11eb-8a9a-8df2ddf67c26.png">

**Comment by polarpixel** [comment]
Ok, Danke, kombiniert mit form-control passt es.
Aber sehr Ihr einen Grund, warum die Breite nicht immer 100% sein sollte, auch ohne dass man form-control mit angibt? Ich z.B. kam nicht auf die Idee, das zu tun.
Und: Der Abstand zwischen Icon-Leiste und Textarea ist damit noch nicht behoben.

**Comment by christophboecker** [comment]
form-control ist so üblich bei allen YForm-Feldern. Das kommt halt aus YForm heraus (.control-label, .form-control)

**Comment by polarpixel** [comment]
Ok, da hast Du recht.
Dann bleibt aber noch der Abstand unter der Icon-Liste.

**Comment by christophboecker** [comment]
Zu Global_Settings kann ich nichts sagen. Beim Abstand: ja, der ist mir auch schon mal aufgefallen und ich habe ihn per Eintrag in meiner Default-BE-CSS erschlagen. Ist halt auch die Frage, wer der "Übeltäter "ist :-) und ob MarkitUp durch YForm-verursachte optische Brüche korrigieren muss oder YForm oder der Systemintegrator oder ob bei MarkitUp Einstellungen fehlen. 

Aber egal, es lässt sich einfach lösen, indem in der markitup/styles.css die Zeile `margin-bottom:0px;` ergänzt wird. Das tut MarkitUp nicht weh und des gibt kein YForm-abhängiges CSS.
```css
.markItUpContainer .markItUpHeader ul {
	list-style:none;
	padding:0px;
	margin-bottom:0px;
}
```

**Comment by polarpixel** [comment]
Fein, genau so dachte ich mir das.
Klar, ich hab das in den letzten Jahren auch immer mit einem eigenen Backend CSS gelöst. Da das aber oft er einzige Grund war, warum ich überhaupt das Backend CSS anlegte, wollte ich das nun einfach mal angehen.
Da der Abstand auch im global_settings-AddOn existiert (und übrigens auch, wenn man ein Artikel-Metafeld mit markitup versieht), würde ich die Ursache nicht primär bei yform suchen und bin der Meinung, markitup sollte hier seinen Abstand mit entsprechendem Nachdruck setzen.
Ich mach mal einen Commit und hoffe, Du bist einverstanden. Rechtfertigt das schon eine neue Version oder willst Du erst noch sammeln?

**Comment by christophboecker** [comment]
Gibt wohl keinen Maintainer aktuell. Und ich, sorry, zieh mir den Schuh auch nicht an. Hau doch einfach eine 3.6.1 raus; Weil Bugfix

**Comment by polarpixel** [comment]
Ah, sorry – da Du hier so fleißig warst in letzter Zeit, dachte ich, Du betreust das derzeit.
Ok, ich mache ein Release, aber erst morgen.
