### ISSUE TITLE
PHP 8 Kompatibilität

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/markitup#120]
Scheint mit PHP 8 nicht mehr zu funktionieren.
Kann irgend jemand helfen? Ich kann es leider nicht.
Kann aber ggf. ein wenig mitfinanzieren.

**Comment by christophboecker** [comment]
Meinst Du das hier?
```
Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in [redaxo/src/addons/markitup/vendor/php-textile/src/Netcarver/Textile/Parser.php](vscode://file//Users/christoph/Sites/focuspoint/test_5_14/redaxo/src/addons/markitup/vendor/php-textile/src/Netcarver/Textile/Parser.php:3256) on line 3256
```
Ich kenn mich mit dem Vendor-Zeugs / Composer nicht aus. Mit etwas Glück müssen nur ein paar Dateien getausucht werden. 
<img width="769" alt="grafik" src="https://user-images.githubusercontent.com/10065904/180052280-bede166a-571c-4da9-9c47-398a777436ef.png">

**Comment by polarpixel** [comment]
Oh, danke für den Hinweis.
Hatte nur bemerkt, dass keine Ausgabe im Frontend erfolgt.
Austauschen werde ich mal ausprobieren.
