### ISSUE TITLE
Kann das weg? Branch "docs"

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/markitup#137]
@alxndr-w Hallo Alex, ich sehe grade, dass Du hier eine Branch "docs" zum Rausoperieren des documentation-Plugins liegen hast. letzte Änderung "last year" wenn ich das richtig sehe.

Da habe ich Dich vermutlich überholt und heute genau das Thema erledigt. Also meinen PR dazu in den Master-Branch gemerged. Das war so ne Folgeaktion aus der Namespace-Umstellung. Kommt dann im beta2-Release; damit will ich aber noch warten ob/bis sich jemand mit Problemen meldet.

**Comment by alxndr-w** [comment]
Kann weg.
