### ISSUE TITLE
Einbindung in YForm

### ISSUE THREAD

**Issue by NGWNGW** [FriendsOfREDAXO/markitup#35]
Hi, 

ich habe eben probiert den Editor in einer YForm Tabelle einzubinden (über die entsprechende Klasse die ich in YForm mitgebe).

Dabei gibt es zwei Probleme:
- Das Textarea Label ist zwischen Iconbar und Textarea positioniert.
- Der Editor funktioniert nicht und schmeißt einen Fehler aus: jquery.markitup.js:491 Uncaught TypeError: Cannot read property 'substring' of undefined

![bildschirmfoto 2016-06-18 um 18 09 37](https://cloud.githubusercontent.com/assets/1823782/16172065/00bb7af4-3580-11e6-814f-07b9c8c977b2.png)

Das liegt wohl daran dass die Klasse nicht der Textarea zugewiesen wird, sondern dem umliegenden Div.

Ich habs nun über eine Custom-Textarea gelöst. Aber wäre praktisch wenn man die normale Textarea von YForm dafür nutzen könnte.

Gruß
Nico

**Comment by skerbis** [comment]
Hi, hierbei handelt es sich um das selbe Problem wie unter https://github.com/yakamara/redaxo_yform/issues/73 - Achtung nach einem Update wird deine custom Textarea wohl gelöscht.

**Comment by phoebusryan** [comment]
Jan ist da dran und es hat ansich nichts mit dem Editor zu tun. Deshalb schliesse ich das hier.

**Comment by alexplusde** [comment]
Wieder geöffnet. Der Workaround, die Klasse "form-control" wieder von Hand hinzuzufügen, sollte mind. in der Hilfe zum Addon erwähnt werden.

**Comment by cukabeka** [comment]
Ich hatte weiterhin Probleme mit YFORM und dem Addon in den aktuellen Versionen. Erst der Hinweis hier hat geholfen. Ggf wäre hilfreich, das schon beim Anlegen der Profile für YFORM mit zu erwähnen.

Funktionierender String in YFORM:
{"class":"form-control markitupEditor-textile_full"}

**Comment by alxndr-w** [comment]
@cukabeka dann mach das doch

https://github.com/FriendsOfREDAXO/markitup/edit/master/README.md
