### ISSUE TITLE
Namen der Buttons

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/markitup#47]
Aktuell heißen die Buttons sehr unterschiedlich, obwohl sie dasselbe machen

```
heading1, heading2 ...
emaillink, externallink, internallink, medialink
groupheading[1|2|3|4|5|6]
grouplink[file|internal|external|mailto]
```

Daher folgende Idee:

```
h1,h2,h3 ...
group[h1,h2,h3]
emaillink, externallink, internallink, medialink
group[emaillink, externallink, internallink, medialink]
```

Die Buttonnamen bleiben gleich, egal ob innerhalb oder außerhalb einer Gruppe. Vorteil wäre auch, dass man sich so eigene Gruppen bilden könnte.

**Comment by phoebusryan** [comment]
Theoretisch ja. Wäre schön. Rein praktisch ist das recht mühsam, da man dann dynamische Configfiles generieren müsste pro Profil. Kannst es gerne versuchen und einen PR schicken..
