### ISSUE TITLE
Addon-Name: `rex_`-Prefix entfernen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/markitup#48]
Der Konsens bei FOR ist, keine Prefixe zu verwenden. Bei einem bereits veröffentlichten Addon ist der Wechsel allerdings mit etwas Aufwand verbunden:

1. Prüfen, ob der neue Addon-Key verfügbar ist
2. Addon mit neuem Key bei MyREDAXO anlegen
3. Repo umbenennen
4. Alte Bezeichnung im gesamten Addon auf neue wechseln
5. Neues Major-Release veröffentlichen mit Hinweis auf neuen Namen
6. Ggfls Hinweis im Forum hinterlassen, denn Nutzer des alten Addons kriegen im Installer keinen Hinweis auf Updates mehr

**Comment by schuer** [comment]
Diskussion im Slack: Die Umbenennung soll erst nach Fertigstellung der neuen Website angegangen werden. Bei der Integration wird es dann vermutlich bessere Möglichkeiten geben als jetzt.

**Comment by phoebusryan** [comment]
https://github.com/redaxo/redaxo/issues/814

**Comment by schuer** [comment]
Im Slack besprochen: Wir nennen das Addon manuell um auf `markitup`.

**Comment by schuer** [comment]
Version 3.0.0 wurde eben unter neuem Namen veröffentlicht. Parallel dazu Version 2.2.0 unter altem Namen mit Hinweis auf die Umbenennung.

Etwas schwierig: Beide Addons nutzen für ihre Konfiguration den gleichen Namen für Tabellen in der Datenbank. Und leider löschen sie diese sowohl beim Deinstallieren als auch beim Installieren (siehe #53). Das bedeutet für unsere Nutzer*innen, die auf das neue Addon wechseln wollen, dass sie in irgendeiner Form ihre Konfiguration vorher sichern und übertragen müssen — oder eben neu anlegen.
— Ich habe eine Info im Installer hinterlegt und hoffe, die Leute kommen damit klar.
