### ISSUE TITLE
Profile werden bei Reinstall gelöscht

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/markitup#53]
Selbst angelegte Profile werden bei Reinstall gelöscht.

**Comment by tbaddade** [comment]
@IngoWinter siehe https://github.com/FriendsOfREDAXO/rex_markitup/issues/14

**Comment by phoebusryan** [comment]
Wieso musst du denn reinstallieren? Das sollte überhaupt nicht mehr relevant sein, da sämtliche SQL-Updates in der update.php ausgeführt werden und die Assets automatisch kopiert werden.

**Comment by IngoWinter** [comment]
Reinstalliert habe ich, um die Assets zu kopieren.

**Comment by phoebusryan** [comment]
Wieso musstest du die Assets kopieren? Ist ein Update schief gelaufen oder so? Bei einem Update werden die Assets automatisch kopiert.

**Comment by IngoWinter** [comment]
Ist doch unerheblich, **warum** ich eine gängige Core Funktion genutzt habe. Das darf mir nicht die Addon Konfiguration zurücksetzen.

**Comment by phoebusryan** [comment]
Das ist relativ. Wenn du etwas deinstallierst und wieder installierst, sind die Settings weg. Das Verhalten ist logisch und bei den anderen Addons auch so.

**Comment by IngoWinter** [comment]
Ich hab aber nix deinstalliert und wieder installiert, ich habe reinstalliert. Im Redaxo Kontext war es immer so, dass dabei die von mir gemachten Einstellungen erhalten bleiben - dafür gibt es mittlerweile sogar extra ein data Verzeichnis. Ich kenne auch kein anderes Addon, das mir ungefragt meinen Kram löscht.
Wenn du keinen Bock oder keine Zeit hast das umzubauen mach ein wontfix/ close und gut ist.

**Comment by phoebusryan** [comment]
> Wenn du keinen Bock oder keine Zeit hast das umzubauen mach ein wontfix/ close und gut ist.

Dein Ernst? Mir geht es überhaupt nicht da drum. Addon die ihre Daten in einer Tabelle speichern, handeln das aktuell so. Das sieht man zum Beispiel auch beim Aufgaben-Addon. Das Data-Verzeichnis ist für Dateien. Ich kann natürlich bei jeder Änderung der Profile Files anlegen, und diese wieder einlesen. Aber ob das eine gescheite Lösung ist, sei mal dahingestellt. Fakt ist, dass ein Reinstall nicht anderes als ein Uninstall/Install ist, was bedeutet, dass die jeweiligen SQL-Dumps ausgeführt werden.

Jedenfalls hat das Problem Thomas Blum ja auch schon bemängelt, da nun aber bei einem Update die Assets automatisch kopiert werden und die Datenbank ebenfalls automatisch angepasst wird, war dies kein Problem mehr.

Ich werde das Issue nicht einfach schliessen, sondern suche eine Diskussionsgrundlage... eben weil das Problem wenn schon alle solche Addons haben.

**Comment by IngoWinter** [comment]
Dann +1 für default_config.json und user_config.json im data/rex_markitup Verzeichnis :)

**Comment by ceekay82** [comment]
Unter der Prämisse, dass man unter einem Re-Install ein Uninstall => Install versteht, erwarte ich sogar, dass meine Daten weg sind. Wenn ich etwas deinstalliere, erwarte ich auch, dass alles weg ist.

Nun kann man ein Re-Install wie Ingo auch anders sehen...

**Comment by gharlan** [comment]
Zum Reinstallieren/Deinstallieren ist unsere Philosophie so:

Deinstallieren: Alle Tabellen, die direkt vom Addon kommen, werden gelöscht. Daten sind also weg.
Reinstallieren: Nichts wird gelöscht, es wird nur versucht, die Installation zu bereinigen bzw. zu korrigieren.

Deinstallieren und anschließend wieder installieren ist also was anderes, als Reinstallieren.
Beim ersten hat man quasi eine frische Installation, beim zweiten nur eine reparierte ohne Datenverlust (soweit möglich).
  
Reinstallieren sollte also eine ungefährliche Aktion sein

Und beim Deinstallieren sollte möglichst viel aufgeräumt werden, also möglichst kein Datenmüll verbleiben.
Dabei gibt es aber Grenzfälle, wo wir uns auch immer nicht so sicher sind, was das richtige Verhalten ist.
Das Backup-Addon zum Beispiel löscht nicht die Backups, ich denke das wäre eine Nummer zu hart. 
Und der yform-manager löscht nur seine Tabellen wo die Tabellen- und Feld-Definitionen drin stehen, aber nicht die eigentlichen Datentabellen. Denn es ist ja durchaus möglich, dass man mit den Tabellen weiter arbeiten möchte, sie nur nicht mehr über yform verwalten möchte. Gehören also nicht unbedingt direkt zum Addon.
