### ISSUE TITLE
help.php entfernen, Inhalte in README.md übertragen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/markitup#55]
REX 5.2 gibt ja inzwischen die README.md als Hilfe aus, wenn keine help.php verfügbar ist.

**Comment by alexplusde** [comment]
Während ich den PR erstellt habe, ist mir aufgefallen, dass die Beschreibung und Hilfe mehrsprachig ist. Wie sollte hier vorgegangen werden?

**Comment by alexplusde** [comment]
Das müsste mit R5.7 nun gelöst sein. Die Frage wäre, ob man jetzt schon eine Abhängigkeit zu R5.7 herstellen möchte. Ich hätte kein Problem damit. Meinungen?

**Comment by schuer** [comment]
Meine Meinung: READMEs mit Sprachkürzel anlegen, so wie vom aktuellen REDAXO erwartet, also etwa `README.en.md`, jedoch nicht die Mindestversion hochsetzen. Das AddOn funktioniert prima in älteren REDAXOs, und die Markdown-Files kann man sich auch im Dateisystem anschauen.

**Comment by alexplusde** [comment]
> Das AddOn funktioniert prima in älteren REDAXOs, und die Markdown-Files kann man sich auch im Dateisystem anschauen.

Weiß das auch der unbedarfte Admin, der das Update einfach so installiert?

**Comment by schuer** [comment]
> Weiß das auch der unbedarfte Admin, der das Update einfach so installiert?

Die Person sieht dann nur die deutschsprachige README, nicht die anderen Sprachen. Fände ich persönlich okay.

**Comment by staabm** [comment]
Finde den vorschlag von dir auch gut
