### ISSUE TITLE
Update von rex_markitup auf die 3.0 Version

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/markitup#57]
Habe soeben von rex_markitup auf markitup umstellen wollen. Dabei blieb `rex_markitup` installiert und habe zusätzlich `markitup` installiert um recht einfach die Profile zu kopieren. Was bleibt sit, dass jetzt alle Profile von `rex_markitup` weg sind.

Entweder sollte eine Fehlermeldung erscheinen, dass `rex_markitup` nicht installiert sein darf oder noch besser `markitup` übernimmt die Profile und löscht sie nicht einfach.

**Comment by phoebusryan** [comment]
Duplicate #53
