### ISSUE TITLE
Interner Link doppelt

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/markitup#62]
Hej,

sobald ich einen internen Link auswähle wird der Code zwei mal in das Textfeld geschrieben...

```dies ist ein "link (Startseite)":redaxo://1" (Startseite)":redaxo://1 test```

Getan: Mit der Maus das Wort _link_ markiert und Internen Link ausgewählt...

**Comment by phoebusryan** [comment]
https://github.com/FriendsOfREDAXO/markitup/issues/60

https://github.com/redaxo/redaxo/issues/1064
