### ISSUE TITLE
Whoops-Seite, wenn SQL-Fehler außerhalb von Markitup

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/markitup#63]
Ich wollte das Textile-Profil ändern und bekam beim Speichern eine Whoops-Seite.

Das Phänomen war, dass die Einstellungen im URL-Plugin von @tbaddade verkehrt waren (Feldname hatte sich geändert, wodurch die Einschränkung nicht mehr funktioniert hat) - dies hätte an der Stelle doch gar keine Auswirkungen haben dürfen?

**Comment by phoebusryan** [comment]
Das sagt mir grade mal gar nichts. Man müsste dem ganzen im Detail mal nachgehen.

**Comment by phoebusryan** [comment]
Ich habe das Ganze nun mal im Detail durchdacht und ich glaube das Issue ist falsch hier. Ich denke, der SQL Fehler beim Ändern des Profiles ist ein Folgefehler. Ich schliesse deshalb hier.
