### ISSUE TITLE
Markdown :: nl to br ?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/markitup#65]
**Eingabe**
```
1. erster Listenpunkt
*kursiver Text*
2. zweiter  Listenpunkt
```

**erzeugte Ausgabe**
```
<ol>
<li>erster Listenpunkt
<em>kursiver Text</em></li>
<li>zweiter Listenpunkt</li>
</ol>
```

**erwünschte Ausgabe** (`<br />` im ersten `<li>`)
```
<ol>
<li>erster Listenpunkt<br />
<em>kursiver Text</em></li>
<li>zweiter Listenpunkt</li>
</ol>
```

**Das erzeugt Github mit obigen Code**, wobei GH noch zwischen Issues und Readme`s unterscheidet

1. erster Listenpunkt
*kursiver Text*
2. zweiter  Listenpunkt

**Comment by tbaddade** [comment]
Ich habe es jetzt für uns so gelöst

```php
return (new \ParsedownExtra)->setBreaksEnabled(true)->text($markup);
```

**Comment by phoebusryan** [comment]
Bin mir gar nicht sicher, was ich mit dem Issue anfangen soll.. :-/

Hilfst du mir mal auf die Sprünge?

**Comment by phoebusryan** [comment]
*reminder*

**Comment by phoebusryan** [comment]
Ist das noch relevant?

**Comment by tbaddade** [comment]
Irgendwie schon … Es geht um den Break (`<br />`) … Man gibt einen break im Textfeld ein, der aber nicht ausgegeben wird.

Vielleicht wird es mit den Beispielen von oben so deutlicher

```
1. erster Listenpunkt
*kursiver Text*
2. zweiter  Listenpunkt
```

```
<ol>
<li>erster Listenpunkt <em>kursiver Text</em></li>
<li>zweiter Listenpunkt</li>
</ol>
```

**Comment by phoebusryan** [comment]
Okay, wie ist deine Codeausgabe? Evtl. wäre dann nämlich das hier relevant:
https://github.com/FriendsOfREDAXO/markitup/blob/master/lib/class.markitup.php#L36

**Comment by phoebusryan** [comment]
Eine gute Frage. Habs das seit dem ersten Commit drin:
https://github.com/FriendsOfREDAXO/markitup/commit/762bab7bdc1410639c955ec6c2363d1862d11fb3#diff-c04d9ebd2be71a02d46384ca0fc814acR38

Keine Ahnung mehr, was der Grund dafür war. Ich kann es mal rausnehmen und schauen ob sich jemand beschwert. ¯\_(ツ)_/¯

**Comment by alexplusde** [comment]
Schon rausgenommen? Oder close?

**Comment by tbaddade** [comment]
Ich schließe wegen Inaktivität.
