### ISSUE TITLE
Eingabe vor dem speichern in die DB via Aktion säubern

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/markitup#68]
Redakteur erstellte leere Überschriften

```
Das ist Blindtext

###
####

Und hier geht es weiter
```

Via Modulaktionen könnte man die Eingabe, vor dem Speichern in die DB, säubern.

**Comment by phoebusryan** [comment]
Was haben Modulaktionen mit meinem Addon zu tun?

**Comment by tbaddade** [comment]
> Was haben Modulaktionen mit meinem Addon zu tun?

- Indem man die Aktion gleich mitliefern könnte
- oder eine Funktion bereitstellen 
   - die über eine Aktion aufgerufen werden kann
   - in der Modulausgabe verwendet wird

**Comment by phoebusryan** [comment]
Ich könnte in der markitup-Klasse eine Methode mitliefern. Die könnte man dann in der Modulausgabe nutzen. Den Inhalt der Methode kann ich aber schlecht selber bauen, da ich die Tücken/Probleme von Textile/Markdown nicht kenne.

**Comment by phoebusryan** [comment]
*reminder*

**Comment by alexplusde** [comment]
Wer verkehrten Syntax mit verwaisten Zeilen eingibt, bekommt imho genau das, was die Person "verdient" ;)

close?

**Comment by tbaddade** [comment]
Ich schließe wegen Inaktivität.
