### ISSUE TITLE
Profile werden jedesmal neu erstellt und vermutlich auch unabhängig vom Benutzer

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/markitup#72]
Ich habe es via ydeploy in der Konsole mitbekommen und ist daher nur eine Vermutung. 

1/ Das Cachefile wird bei jedem Backendaufruf erzeugt
2/ Als Sprache für die Buttonnamen wird die Backendsprache des Benutzers verwendet, der grad die Seite aufruft.
3/ Ist ein User mit deutscher Backendsprache unterwegs, könnte es durchaus passieren das er die Buttonnamen nicht in deutscher Sprache sieht. Das passiert, sobald sich ein zweiter User mit anderer Backendsprache einloggt.

Stimmen die Vermutungen @phoebusryan 
Wäre das beim Redactor identisch?

**Comment by phoebusryan** [comment]
Das ist alles aktuell so:
https://github.com/FriendsOfREDAXO/redactor2/issues/98
