### ISSUE TITLE
Tabellen funktionieren nicht?

### ISSUE THREAD

**Issue by georgkaser** [FriendsOfREDAXO/markitup#74]
Kann es sein, dass Tabellen nicht funktionieren? Bei mir wird | ABC | ABC | | ABC | ABC | nicht in eine Tabelle umgewandelt. Muss ich da irgendwas einstellen?

**Comment by phoebusryan** [comment]
nutzt du textile oder markdown?

**Comment by georgkaser** [comment]
markdown - mit textile funktionieren sie...

**Comment by georgkaser** [comment]
Hochstellen geht auch nicht: m^2^. Scheint als arbeitet Parsedown nicht richtig?

**Comment by phoebusryan** [comment]
Ich nutze hier eigentlich die die Version aus dem Core. Ist das Probleme generell bekannt so? Wie ist denn deine Ausgabe?

**Comment by meugel** [comment]
Scheint immer noch nicht zu funktionieren. Hbe gerade Version 3.3.0 installiert. Keine Tabellen mit Markdown.

**Comment by polarpixel** [comment]
Ich kam durch das Forum auf dieses Issue.

Diese Eingabe hier funktioniert:
```
Spalte 1 | Spalte 2 | Spalte 3
-------- | -------- | --------
Inhalt   | Inhalt   | Inhalt
Inhalt   | Inhalt   | Inhalt
```

Ohne Definition der Spaltenköpfe jedoch nicht.
Es hängt vom Parser ab, ob es ohne Spaltenköpfe funktioniert oder nicht:
https://stackoverflow.com/questions/17536216/create-table-without-header-in-markdown

@georgkaser, dann könnte man das Issue schließen, oder?

**Comment by georgkaser** [comment]
Denke wenn’s funktioniert dann ja :)
