### ISSUE TITLE
Profile Cache Dateien werden bei jedem click neu geschrieben

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/markitup#80]
sobald das addon installiert ist, werden bei jedem click eines users im backend 2 cache dateien geschrieben

https://github.com/FriendsOfREDAXO/markitup/blob/55e1ed43288908e395e22c31131a0b1fe7177e80/boot.php#L43-L49

das sollte unbedingt vermieden werden, da es die performance des backends beeinflusst.

können wir irgendwie erreichen dass diese dateien nur dann neu geschrieben werden, wenn sich die profile/ein profil tatsächlich ändern/ändert?

**Comment by staabm** [comment]
das problem ist wohl leider schon lange bekannt und als teil eines anderen issues auch schonmal benannt worden
https://github.com/FriendsOfREDAXO/markitup/issues/72

**Comment by staabm** [comment]
vorschlag: die vorhandene rex_markitup_profiles tabelle erweitern um createdate/updatedate spalten (wie fast überall im core) und in der boot.php via addon-config und dem zeitstempel aus der db erkennen, ob sich was geändert hat.

falls sich was geändert hat, cache dateien neu schreiben.

**Comment by phoebusryan** [comment]
Eine Lösung gibt es eigentlich schon, muss nur umgesetzt werden:
https://github.com/FriendsOfREDAXO/markitup/issues/72

Also Profile cachen und bei Änderungen Cache löschen. An sich easy.

**Comment by staabm** [comment]
Auch diese Lösung wäre ok, es sollte aber bald eine her :-)

**Comment by christophboecker** [comment]
Evtl hab ich das Problem nicht komplett verstanden ... Meine Lösung für so was wäre, die beiden Dateien immer dann neu anzulegen, wenn ein Profile gespeichert/geändert wird. Oder ist das zu schlicht gedacht?

**Comment by staabm** [comment]
Jepp das ist was phoesbyan oben gemeint hat.

Siehe ähnliche Lösung in https://github.com/FriendsOfREDAXO/redactor2/commit/40900632283b2c3496641733a0b75d7ba026c744

**Comment by christophboecker** [comment]
Ich schau mal, kann aber ein paar Tage dauern bis der PR kommt. Bei der Gelegenheit könnte ich #76 mit einbauen. Wie ist die Meinung zu dem Vorschlag?

**Comment by staabm** [comment]
Ich verwende markitup selbst nicht, daher hab ich keine Meinung zu #76 .

Falls du beides umsetzen willst, bitte in getrennten PRs

**Comment by christophboecker** [comment]
Die Frage auch eher an Thomas (@phoebusryan) gerichtet und ist auch nicht soooo wichtig. ich mache halt nix auf Verdacht, nur wenn vorab grünes Licht. 

Und klar, getrennte PRs.

**Comment by christophboecker** [comment]
Thomas (@phoebusryan), sag mal was Dir lieber ist:

Hintergrund: Wenn die beiden Dateien zukünftig nur noch bei Änderungen der Profiltabelle neu erzeugt werden, muss es ja einen Mechanismus geben, der die erste Erstellung (bevor es eine Änderung der Tabelle gab) sicherstellt. 

Mir fallen dafür zwei Varianten ein: via install.php oder sie sind schon vorgefertig in markitup/assets. 

Die install.php wäre meine bevorzugte Lösung, aber dann ist das Problem, dass die install.sql noch gar nicht ausgeführt wurde (passiert im package-manager erst nach der install.php). Nen EP habe ich auch nicht gefunden. Das wäre also ein etwas größerer Umbau (Ziel: alles über install.php steuern). Den stelle ich mir so vor:

* install.sql umbenennen in default.sql (damit keine install.sql ausgeführt wird)
* install.php importiert die default.sql und legt dann die beiden Dateien an.

Die andere Lösung ist simpler, hat aber den Nachteil, dass man bei Änderungen am Default-Setup an ein Update an *zwei*  Stellen denken muss: die beiden Dateien und die install.sql.

Welche Variante hättest Du gerne?

Grüße
Chris

**Comment by staabm** [comment]
Man könnte in der boot auch ein if-file-not-exists -> generate cache reinbauen

**Comment by christophboecker** [comment]
Dann wird wieder bei jedem Click unnötig über die Platte geschrubbelt. Wenn dann richtig.

Von meinem Kühlschrank gesendet.

**Comment by staabm** [comment]
Alles was in diese Richtung geht ist welten besser als das was wir aktuell haben :-). 

Aber zu deinem Problem. Alternativ die install.sql in eine install.php überführen (ist ohnehin die stabilere variante) und dann kannst du mach anlage der tabelle und daten direkt nach install den cache generieren

**Comment by phoebusryan** [comment]
Ich bin aktuell leider sehr sehr sehr ausgelastet, hab es aber nicht vergessen. Ich werde es asap fertigstellen. Wenn es wirklich dringend ist (und davon gehe ich aus, da ich bereits einige Anfragen hatte), dürft ihr das ganze gerne direkt selber fixen. Ich wäre auch bereit den Lead für das markitup-Addon abzugeben, da ich es selbst gar nicht nutze und es ursprünglich für @polarpixel gebaut habe. :-)

**Comment by phoebusryan** [comment]
Das ist ja glaube ich nun bereits umgesetzt worden. Deshalb schliesse ich hier mal.
