### ISSUE TITLE
markdownExtra Unterstützung

### ISSUE THREAD

**Issue by sjewo** [FriendsOfREDAXO/markitup#82]
Hallo zusammen!

Ich würde das Addon gerne zum parsen von markdownExtra nutzen. Wenn ich richtig sehe, ist das standardmäßig nicht vorgesehen. 
Ich habe dafür einfach einen neuen Parsertyp angelegt und es funktioniert bisher problemlos. 

Falls gewünscht, kann ich einen pull request machen: 5a1802fd4870ae00444fba8e624c94784bdf6892

**Comment by tbaddade** [comment]
Du könntest das auch über 

```
echo rex_markdown::factory()->parse($string);
```

machen

**Comment by sjewo** [comment]
Dann nutze ich aber doch auch nur die Klasse `parsedown` und nicht `parsedownExtra` oder?

**Comment by tbaddade** [comment]
> Dann nutze ich aber doch auch nur die Klasse parsedown und nicht parsedownExtra oder?

nein, siehe [hier](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/lib/util/markdown.php#L19)

**Comment by sjewo** [comment]
Ok. Jetzt verstehe ich! Hab an der falschen Stelle geguckt. So ist es einfacher.
