### ISSUE TITLE
Interner Link

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/markitup#85]
clang wird nicht übergeben. So wird immer die Linkmap der 1. Sprache angezeigt.

**Comment by phoebusryan** [comment]
guter Punkt. Nehme ich auf. Haue demnächst eh einen neuen Release raus :)

**Comment by phoebusryan** [comment]
Habs mir grade noch angeschaut im Detail. Wieso genau tritt das auf? Wenn ich die Backendsprache auf englisch setze, wird die Linkmap in englisch geöffnet (was ja glaube ich nicht das ist was du meinst). Wenn ich dann einen Link auswähle, habe ich im Code dann
`"Test (Test [8])":redaxo://8` stehen. Das ganze wird dann ja von Redaxo selbst geparsed..

**Comment by isospin** [comment]
Ich frage mich gerade warum die ID des Artikels mit im Title Tag landet:
`"Test (Test [8])":redaxo://8`

**Comment by willigimbel** [comment]
markitup v3.6.0

Ich habe gerade versucht in einer zweiten Sprache den Linkmap zu öffnen, um einen internen Link zu erzeugen. Es wird nur die Linkmap der Sprache mit der ID 1 gezeigt.
Ist das korrekt?

**Comment by IngoWinter** [comment]
Ja. es wird ja nur die sprachunabhängige ID des zu verlinkenden Artikels eingesetzt.

**Comment by willigimbel** [comment]
Mein Gott bist Du schnell. Entschuldige wenn ich das nur schwer verstehe, dh ich kann markitup nur in einsprachigen Websites verwenden? Unter Redaxo 4 war markitup so: wenn ich innerhalb ver deutsch Seite war wurden die deutschen Artikel / Kategorien in der Linkmap gezeigt. Wenn ich mich beim editieren in einer anderen Sprache befand die der Linkmap in dieser Spache auf.

Ich verstehe nicht wie ich nun im Englischen Teil der Seite einen internen Link herstellen könnte. HG

**Comment by IngoWinter** [comment]
Klick im Baum einfach auf den deutschen Artikel, der dem englischem enspricht. Es wird dann der englische verlinkt. Hoffe ich jedenfalls :)

**Comment by willigimbel** [comment]
Oh, ja – Du hast recht, das geht. 
Das ist verwirrend für einen Redakteur, auch nicht besonders übersichtlich, weil nicht alle Kategorien / Artikel üblicherweise in allen Sprachen online sind und abgesehen von den anderen Namen dann auch andere Farben (grün/rot) haben aber ...

MANN bin ich dankbar für Deine irrsinnig schnelle Hilfe und ich bin froh das es überhaupt geht :)

**Comment by IngoWinter** [comment]
Einfach behaupten das sein ein Feature und der Entwickler rot/grün blind - Problem gelöst 👍

**Comment by skerbis** [comment]
👀hmm - eigentlich war das hier schon mal gelöst

**Comment by willigimbel** [comment]
Ich kann nicht programmieren, ich frickel mir Sachen so lange zusammen bis es nicht mehr explodiert. 
Ich hab jetzt folgendes in scripts.js ersetzt:
(aus https://stackoverflow.com/questions/901115/how-can-i-get-query-string-values-in-javascript)

//var linkMap = openLinkMap();
const urlParams = new URLSearchParams(window.location.search);
const clangID = urlParams.get('clang');
var linkMap = openLinkMap('', '&clang='+ clangID);

Das geht. 
Bestimmt könnt ihr das Redaxo-haft schöner machen. Ich bin wie immer dankbar für euer Können.

**Comment by willigimbel** [comment]
sorry geht doch nicht. der Link ist am Ende falsch gesetzt. ich geb auf
