### ISSUE TITLE
rex_markitup.buttondefinitions ?

### ISSUE THREAD

**Issue by danielellm** [FriendsOfREDAXO/markitup#89]
wie und wo kann ich die button definieren

**Comment by phoebusryan** [comment]
Im Profil im Backend unter dem Punkt 'MarkItUp'

**Comment by tbaddade** [comment]
@phoebusryan Funktioniert das ähnlich wie beim Redactor2, wenn ich eigene Buttons einbinden will?

**Comment by phoebusryan** [comment]
Eigene Buttons gibts da gar nicht. Nur die vorgegeben. Hab es nicht so verstanden, dass es um Custom-Buttons geht.

**Comment by steri-rex** [comment]
ich würde gerne eigene Buttons einbinden (Custom-Buttons) - hab ich es richtig verstanden das das nicht geht? oder gibt es eine Möglichkeit?

**Comment by phoebusryan** [comment]
Aktuell nicht, nein. Wäre aber nicht so schwierig zu erweitern. Was fehlt dir denn?

**Comment by steri-rex** [comment]
ich ziehe eine ältere rex4 webseite auf rex5 hoch - in rex4 hatte ich das markitup addon verwendet und eigene buttons gemacht - z.b. einen button für einen Absatz klein - da kam dann <p class="klein"></p> raus - nun würde ich gerne diese 3 selbst definierten buttons wieder hinzufügen

**Comment by christophboecker** [comment]
Hi steri-rex, ist das Thema noch aktuelle? (jedenfalls ist es nicht geschlossen). Schau mal in die Profil-Definitionen. Da kannst Du "snippets" definieren, die dann aber kein eigener Button sind, sondern in einem DropDown-Menü erscheinen. Besser als nix. By the way: ich hab da mal ne Snippet-Verwaltung programmiert (https://github.com/christophboecker/markitup/tree/snippets). Der PR dazu ist noch offen, kannst Dir aber gerne mein Repository ziehen und testen.

**Comment by alexplusde** [comment]
Hier gibt es Lösungsansätze:
https://stackoverflow.com/questions/1427193/customizing-the-markitup-toolbar

Man müsste, wenn ich das richtig verstehe, dann an Markitup-Profilen ein zusätzliches Eingabefeld für so etwas hinterlegen.

Möchte das jemand weiter verfolgen?

**Comment by willigimbel** [comment]
Gerade auch das Problem gehabt. Beispiel hier bezieht sich nur auf Textile.

In der config.yml und der style.css lassen sich neue Buttons anlegen. Bezogen auf Beispiel oben:

config.yml: 
p_klein:
    name: profiles_buttons_p_klein
    className: p_klein
    openWith:
        markdown: '\n\n'
        textile: "p(klein). "

style.css:
.markItUpContainer .markItUpHeader > ul > li.p_klein > a:before {content: "\f1dd";}
.markItUpContainer .markItUpHeader > ul > li.p_klein > a:after {content: "1";} 
(oder etwas anderes sinnvolles statt content: "1")
