### ISSUE TITLE
UI nicht touch-kompatibel

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/markitup#90]
Gruppierte Elemente, bspw. Links, können nicht per Touch bedient werden

**Comment by phoebusryan** [comment]
PR willkommen :P

Das Problem ist, dass markitup eigentlich einen Vendor ist, der schon lange nicht mehr weiterentwickelt wird. Aber evtl. ist das Problem ja simpel lösbar.

**Comment by alexplusde** [comment]
Öh, ich erwarte keinen fix. Vielleicht gibt es ja eine vendor-alternative für die GUI.

**Comment by phoebusryan** [comment]
Möglicherweise... Hab mal das hier angeschaut:
https://simplemde.com/

**Comment by alexplusde** [comment]
Das wäre dann nicht für textile, oder?

**Comment by phoebusryan** [comment]
Könnte man sicher aufbohren :-)

War nur mal ein Gedanke. Habe mich noch nicht genauer damit beschäftigt.

**Comment by alexplusde** [comment]
Laut Github wurde die Entwicklung von markitup generell eingestellt. Auch Version 2 wurde seit 7 Jahren nicht angefasst. Das letzte Update in 1.x in 6 Jahren war die MIT-Lizenz.

Vielleicht findet man etwas Zeitgemäßes, das auch aktiv gewartet wird?
