### ISSUE TITLE
neues release erstellen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/markitup#92]
kann jemand ein release erstellen und in den installer laden?

**Comment by staabm** [comment]
@schuer  vllt?

**Comment by staabm** [comment]
oder @skerbis ?

**Comment by skerbis** [comment]
Ja ich teste und mach das

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/markitup/releases/tag/3.2.0

**Comment by phoebusryan** [comment]
Ähm. Danke. Warum war das nötig?
