### ISSUE TITLE
Editor Eingabe: Zwei Leerzeilen vor und nach Headline …

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/markitup#97]
Würde hier nicht jeweils eine reichen?

**Comment by alexplusde** [comment]
Wie war deine Eingabe?

**Comment by ansichtsache** [comment]
wort markiert und dann über die symbolleiste headline gewählt.
ich persönlich brauche das nicht – h2. tippen geht schneller – aber die kunden benutzen das gerne mal. und dann braucht der text im textfeld 'ne menge luft wegen der doppelten leerzeilen.

**Comment by alexplusde** [comment]
Ah, verstehe... Das Problem ist wohl, wenn man das Zeilenende mitnimmt. Der Kunde könnte alternativ den Button klicken und dann schreiben - ohne Markierung wird meines Wissens auch keine Leerzeile erzeugt.
